### ISSUE TITLE
Error message: Could not anaylze selected file 

### ISSUE THREAD

**Issue by Alg3r** [Rafostar/gnome-shell-extension-cast-to-tv#131]
Hi!

The extension is working for other files and I can run this file using mpv or vlc.

I'm using Gnome 3.38.2

The following error message appears when I try to cast file "test_sample.mkv" from Archlinux to Chromecast:
`Nie można przeanalizować wybranego pliku: /home/mateusz/test cast/test_sample.mkv`
It is polish translation of: Could not anaylze selected file.

Is this the problem with the file or something does not work correctly with extension ?
If the problem is the file what can I do?
I tried it with and without transcoding.

Output of ffprobe on file:
```
ffprobe -show_streams -show_format -print_format json test_sample.mkv 
ffprobe version n4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 10.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
{
[matroska,webm @ 0x5626e87622c0] Could not find codec parameters for stream 4 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, matroska,webm, from 'test_sample.mkv':
  Metadata:
    encoder         : libebml v1.4.0 + libmatroska v1.6.2
  Duration: 00:01:01.51, start: 0.000000, bitrate: 18989 kb/s
    Chapter #0:0: start 0.000000, end 61.512000
    Metadata:
      title           : Chapter 01
    Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1600 [SAR 1:1 DAR 12:5], 24 fps, 24 tbr, 1k tbn, 24 tbc (default)
    Metadata:
      BPS-eng         : 14283395
      DURATION-eng    : 00:01:01.500000000
      NUMBER_OF_FRAMES-eng: 1476
      NUMBER_OF_BYTES-eng: 109803605
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: truehd, 48000 Hz, 7.1, s32 (24 bit) (default)
    Metadata:
      title           : Atmos 7.1
      BPS-eng         : 3856977
      DURATION-eng    : 00:01:01.500000000
      NUMBER_OF_FRAMES-eng: 73800
      NUMBER_OF_BYTES-eng: 29650516
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s
    Metadata:
      title           : AC-3 5.1
      BPS-eng         : 640000
      DURATION-eng    : 00:01:01.504000000
      NUMBER_OF_FRAMES-eng: 1922
      NUMBER_OF_BYTES-eng: 4920320
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(eng): Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : Commentary
      BPS-eng         : 131532
      DURATION-eng    : 00:01:01.483000000
      NUMBER_OF_FRAMES-eng: 2882
      NUMBER_OF_BYTES-eng: 1010878
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(ger): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : ger
      BPS-eng         : 42993
      DURATION-eng    : 00:00:31.958000000
      NUMBER_OF_FRAMES-eng: 13
      NUMBER_OF_BYTES-eng: 171750
      _STATISTICS_WRITING_APP-eng: mkvmerge v50.0.0 ('Awakenings') 64-bit
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    "streams": [
        {
            "index": 0,
            "codec_name": "hevc",
            "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",
            "profile": "Main 10",
            "codec_type": "video",
            "codec_time_base": "1/24",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 3840,
            "height": 1600,
            "coded_width": 3840,
            "coded_height": 1600,
            "closed_captions": 0,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "12:5",
            "pix_fmt": "yuv420p10le",
            "level": 153,
            "color_range": "tv",
            "color_space": "bt2020nc",
            "color_transfer": "smpte2084",
            "color_primaries": "bt2020",
            "refs": 1,
            "r_frame_rate": "24/1",
            "avg_frame_rate": "24/1",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "BPS-eng": "14283395",
                "DURATION-eng": "00:01:01.500000000",
                "NUMBER_OF_FRAMES-eng": "1476",
                "NUMBER_OF_BYTES-eng": "109803605",
                "_STATISTICS_WRITING_APP-eng": "mkvmerge v50.0.0 ('Awakenings') 64-bit",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
            }
        },
        {
            "index": 1,
            "codec_name": "truehd",
            "codec_long_name": "TrueHD",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "s32",
            "sample_rate": "48000",
            "channels": 8,
            "channel_layout": "7.1",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bits_per_raw_sample": "24",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "title": "Atmos 7.1",
                "BPS-eng": "3856977",
                "DURATION-eng": "00:01:01.500000000",
                "NUMBER_OF_FRAMES-eng": "73800",
                "NUMBER_OF_BYTES-eng": "29650516",
                "_STATISTICS_WRITING_APP-eng": "mkvmerge v50.0.0 ('Awakenings') 64-bit",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
            }
        },
        {
            "index": 2,
            "codec_name": "ac3",
            "codec_long_name": "ATSC A/52A (AC-3)",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 6,
            "channel_layout": "5.1(side)",
            "bits_per_sample": 0,
            "dmix_mode": "-1",
            "ltrt_cmixlev": "-1.000000",
            "ltrt_surmixlev": "-1.000000",
            "loro_cmixlev": "-1.000000",
            "loro_surmixlev": "-1.000000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 8,
            "start_time": "0.008000",
            "bit_rate": "640000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "title": "AC-3 5.1",
                "BPS-eng": "640000",
                "DURATION-eng": "00:01:01.504000000",
                "NUMBER_OF_FRAMES-eng": "1922",
                "NUMBER_OF_BYTES-eng": "4920320",
                "_STATISTICS_WRITING_APP-eng": "mkvmerge v50.0.0 ('Awakenings') 64-bit",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
            }
        },
        {
            "index": 3,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 17,
            "start_time": "0.017000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "title": "Commentary",
                "BPS-eng": "131532",
                "DURATION-eng": "00:01:01.483000000",
                "NUMBER_OF_FRAMES-eng": "2882",
                "NUMBER_OF_BYTES-eng": "1010878",
                "_STATISTICS_WRITING_APP-eng": "mkvmerge v50.0.0 ('Awakenings') 64-bit",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
            }
        },
        {
            "index": 4,
            "codec_name": "hdmv_pgs_subtitle",
            "codec_long_name": "HDMV Presentation Graphic Stream subtitles",
            "codec_type": "subtitle",
            "codec_time_base": "0/1",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 61512,
            "duration": "61.512000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "ger",
                "title": "ger",
                "BPS-eng": "42993",
                "DURATION-eng": "00:00:31.958000000",
                "NUMBER_OF_FRAMES-eng": "13",
                "NUMBER_OF_BYTES-eng": "171750",
                "_STATISTICS_WRITING_APP-eng": "mkvmerge v50.0.0 ('Awakenings') 64-bit",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
            }
        }
    ],
    "format": {
        "filename": "test_sample.mkv",
        "nb_streams": 5,
        "nb_programs": 0,
        "format_name": "matroska,webm",
        "format_long_name": "Matroska / WebM",
        "start_time": "0.000000",
        "duration": "61.512000",
        "size": "146006922",
        "bit_rate": "18989065",
        "probe_score": 100,
        "tags": {
            "encoder": "libebml v1.4.0 + libmatroska v1.6.2"
        }
    }
}
```

Log message from extension using following commands:
```
cd ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts
DEBUG=bridge,ffmpeg,chromecast,ffmpeg-extract* node server
```

There are two attempts in log first one without transcoding and second with transcoding.
Message does not change.
Log:

```
 bridge Full playlist: ["/home/mateusz/test cast/test_sample.mkv"] +0ms
  bridge New selection contents: {"streamType":"VIDEO","subsPath":"","filePath":"/home/mateusz/test cast/test_sample.mkv"} +1ms
  bridge Processing video file... +0ms
  bridge No reusable subtitles file +3ms
  ffmpeg-extract Analyzing: /home/mateusz/test cast/test_sample.mkv +0ms
  ffmpeg-extract Successfully analized: /home/mateusz/test cast/test_sample.mkv +28ms
  bridge Searching for preferred subtitles: eng/English +28ms
  ffmpeg-extract:video Searching for requested subtitles lang: eng +0ms
  ffmpeg-extract:video Requested subtitles lang not found +1ms
  ffmpeg-extract:video Searching for requested subtitles lang: english +0ms
  ffmpeg-extract:video Requested subtitles lang not found +0ms
  bridge Searching for fallback subtitles: pol/Polish +1ms
  ffmpeg-extract:video Searching for requested subtitles lang: pol +0ms
  ffmpeg-extract:video Requested subtitles lang not found +0ms
  ffmpeg-extract:video Searching for requested subtitles lang: polish +0ms
  ffmpeg-extract:video Requested subtitles lang not found +0ms
  bridge Requested subtitles track not found +0ms
  bridge Extracting video subtitles... +0ms
  ffmpeg-extract:shared Convert opts: {"file":"/home/mateusz/test cast/test_sample.mkv","outPath":"/tmp/test_sample.vtt","overwrite":true,"vttparser":true,"streamIndex":null,"isVideo":true,"charEnc":"UTF-8","spawnArgs":["-sub_charenc","UTF-8","-i","/home/mateusz/test cast/test_sample.mkv","-f","webvtt","pipe:1"],"ffmpegPath":"/usr/bin/ffmpeg"} +0ms
  ffmpeg-extract:vtt-parser Started vtt-parser +0ms
  ffmpeg-extract:vtt-parser Stream from ffmpeg is closed +24ms
  bridge Error: Parser output is empty
  bridge     at Interface.onReadClose (/home/mateusz/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_modules/ffmpeg-extract/lib/vtt-parser.js:95:14)
  bridge     at Object.onceWrapper (node:events:482:28)
  bridge     at Interface.emit (node:events:388:22)
  bridge     at Interface.close (node:readline:429:8)
  bridge     at Socket.onend (node:readline:202:10)
  bridge     at Socket.emit (node:events:388:22)
  bridge     at endReadableNT (node:internal/streams/readable:1294:12)
  bridge     at processTicksAndRejections (node:internal/process/task_queues:80:21) +27ms
Cast to TV: Nie można przeanalizować wybranego pliku: /home/mateusz/test cast/test_sample.mkv
  bridge New selection contents: {"streamType":"VIDEO_VENC_AENC","subsPath":"","filePath":"/home/mateusz/test cast/test_sample.mkv"} +4m
  bridge Processing video file... +0ms
  bridge No reusable subtitles file +1ms
  ffmpeg-extract Analyzing: /home/mateusz/test cast/test_sample.mkv +4m
  ffmpeg-extract Successfully analized: /home/mateusz/test cast/test_sample.mkv +44ms
  bridge Searching for preferred subtitles: eng/English +44ms
  ffmpeg-extract:video Searching for requested subtitles lang: eng +4m
  ffmpeg-extract:video Requested subtitles lang not found +0ms
  ffmpeg-extract:video Searching for requested subtitles lang: english +0ms
  ffmpeg-extract:video Requested subtitles lang not found +0ms
  bridge Searching for fallback subtitles: pol/Polish +0ms
  ffmpeg-extract:video Searching for requested subtitles lang: pol +0ms
  ffmpeg-extract:video Requested subtitles lang not found +0ms
  ffmpeg-extract:video Searching for requested subtitles lang: polish +0ms
  ffmpeg-extract:video Requested subtitles lang not found +0ms
  bridge Requested subtitles track not found +0ms
  bridge Extracting video subtitles... +0ms
  ffmpeg-extract:shared Convert opts: {"file":"/home/mateusz/test cast/test_sample.mkv","outPath":"/tmp/test_sample.vtt","overwrite":true,"vttparser":true,"streamIndex":null,"isVideo":true,"charEnc":"UTF-8","spawnArgs":["-sub_charenc","UTF-8","-i","/home/mateusz/test cast/test_sample.mkv","-f","webvtt","pipe:1"],"ffmpegPath":"/usr/bin/ffmpeg"} +4m
  ffmpeg-extract:vtt-parser Started vtt-parser +4m
  ffmpeg-extract:vtt-parser Stream from ffmpeg is closed +40ms
  bridge Error: Parser output is empty
  bridge     at Interface.onReadClose (/home/mateusz/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_modules/ffmpeg-extract/lib/vtt-parser.js:95:14)
  bridge     at Object.onceWrapper (node:events:482:28)
  bridge     at Interface.emit (node:events:388:22)
  bridge     at Interface.close (node:readline:429:8)
  bridge     at Socket.onend (node:readline:202:10)
  bridge     at Socket.emit (node:events:388:22)
  bridge     at endReadableNT (node:internal/streams/readable:1294:12)
  bridge     at processTicksAndRejections (node:internal/process/task_queues:80:21) +43ms
Cast to TV: Nie można przeanalizować wybranego pliku: /home/mateusz/test cast/test_sample.mkv
^C
Cast to TV: closing node app...
  bridge Closing node server +7m
Cast to TV: closed successfully
```

Let me know if you need more information.

**Comment by Rafostar** [comment]
Coś jest nie tak z napisami w tym filmie. Według analizy są w nim zawarte napisy po niemiecku, jednak ich wykryta długość coś nie pasuje do filmu. Przyczyną są te napisy lecz ciężko mi stwierdzić, czy dałoby się to poprawić w samym rozszerzeniu bez dostępu do omawianego pliku :disappointed: 

Jednym z rozwiązań tutaj mogłoby być dodanie opcji, aby "olać" napisy nie pasujące do wybranych języków (czyli u ciebie ang i pol), wtedy parser napisów by nie próbował przetworzyć tych niemieckich napisów i się tutaj nie wywalił. Ale to tylko rozwiązanie do tego konretnego pliku, bo nie ma gwarancji, że następnym razem ktoś nie napotka podobnego problemu z analizą napisów w ich ojczystym języku...

**Comment by Alg3r** [comment]
Usunąłem niepoprawne napisy z pliku używając MKVToolNix i plik działa poprawnie.

Czas trwania napisów może nie pasować do pliku, bo jest to fragment większego pliku.
Niestety udostępnienie pliku może być problematyczne z powodów legalnych.
Problemem może nie być udostępnienie oryginalnej nazwy pliku: unhinged.2020.2160p.uhd.bluray.x265-unhinged.sample.mkv

Jak opisałeś naprawienie tego problemu wymagało by dodatkowych akcji z napisami i omijanie błędnych napisów.
W takim wypadku można pomyśleć nad jakaś informacją dla użytkownika jaki jest problem z plikiem ?
Aktualnie użytkownik dostaje lakoniczną i niepomocną informacje, że nie można przeanalizować pliku.

Jeżeli już dodamy informacje jaki jest problem z plikiem to może najprostsze rozwiązanie to jakiś popup lub możliwość wyłączenia odczytywania napisów z pliku na poziomie Nautilusa / okna wyboru pliku ?
Pozwoli to użytkownikowi zdecydować co zrobić dalej.

**Comment by Rafostar** [comment]
> W takim wypadku można pomyśleć nad jakaś informacją dla użytkownika jaki jest problem z plikiem ?

Problem w tym, że program jedynie wie że wystąpił error podczas analizy pliku. Ciężko by mu było samemu stwierdzić co w tym pliku jest nie tak, a co dopiero dokonać samodzielnej naprawy (tu były napisy, ale przyczyn może być setka). Ja to byłem dopiero w stanie stwierdzić po oglądnięciu obydwu logów które mi podesłałeś.

Program do analizy jest zupełnie gdzie indziej, a jedyne co dostajemy od niego z powrotem to error o pewnej treści. Rozszerzenie nie jest w stanie przeczytać ze zrozumieniem tego typu komunikatu. Dlatego zrobiłem że wysyła na pulpit komunikat, że analiza zawiodła, bo lepsze to niż brak jakiegokolwiek powiadomienia.

**Comment by Alg3r** [comment]
Jeżeli program do analizy nie dostarcza dodatkowych informacji to nic nie poradzimy.

W takim wypadku jak wygląda możliwość dodania opcji wyłączania analizy/obsługi napisów dla konkretnego pliku ?

**Comment by Rafostar** [comment]
> W takim wypadku jak wygląda możliwość dodania opcji wyłączania analizy/obsługi napisów dla konkretnego pliku ?

To jest do zrobienia. Nie jestem w stanie jednak powiedzieć na kiedy, bo ostatnio pochłonięty jestem pracą nad innym multimedialnym programem (nie związanym z Chromecastem).

**Comment by Alg3r** [comment]
No to czekam w spokoju na wprowadzenie tej funkcjonalności w przyszłości.

Na ten moment wiem co może być problemem w przyszłości i samodzielnie mogę usuwać napisy z plików dla sprawdzenia czy plik zacznie działać.

Jak rozumie program do analizy to narzędzie zewnętrzne.
Jest sens zgłaszania tego jako problem narzędzia, wiedząc że nie mogę dostarczyć pliku a jedynie logi?
Istnieje jakieś repozytorium z Issue do tego toola ?

Zdecyduj czy zostawiamy Issue otwarte do czasu implementacji czy zamykamy.
Jak otwarte to może krótkie podsumowanie dla reszty świata po angielsku ?

**Comment by Rafostar** [comment]
> Jest sens zgłaszania tego jako problem narzędzia, wiedząc że nie mogę dostarczyć pliku a jedynie logi?
Istnieje jakieś repozytorium z Issue do tego toola ?

Jak będę nad tym pracował to sam się tym też zajmę.

> Zdecyduj czy zostawiamy Issue otwarte do czasu implementacji czy zamykamy.

Najlepiej by było jakbyś otworzył nowe Issue z tytułem typu `[FR] Allow ignoring invalid merged subtitles` czy coś w tym stylu i w treści krótko jedynie opisał że miałeś ten problem, co zrobiłeś by go obejść (logi nie będą raczej już tam potrzebne) i że dlatego sobie tego życzysz. Oczywiście po angielsku dla reszty świata, bo z naszej polskiej gadki tutaj i tak nikt by nic nie zrozumiał :smile:

**Comment by Alg3r** [comment]
Zamykam to Issue.
Nowy feature request został dodany
