### ISSUE TITLE
Casting not working

### ISSUE THREAD

**Issue by nhillsdonuk** [Rafostar/gnome-shell-extension-cast-to-tv#137]
1. After a fresh install of this extension and it's node modules from extension prefs, usually a reboot fixes this issue (and by reboot I mean full system reboot - not just restarting gnome-shell).

2. Make sure you have receiver type in extension prefs set correctly to desired device type (e.g. "Chromecast"). If it wasn't try casting again.

3. If extension seems to be working (you have a top panel drop down menu), but still experiencing problems with casting, lets take a look at what happens during file cast. Turn off this extension node service without disabling whole extension (from gnome top bar menu). TV indicator icon should disappear from top bar. Then do the following in terminal:

```
cd ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts
DEBUG=bridge,chromecast* node server
```

After running, extension menu and indicator should reappear.
Try reproducing your problem and send me output. Stop the terminal process with Ctrl+c buttons.

Output:
```
cd ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts
DEBUG=bridge,chromecast* node server
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.listen (/home/nick/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/nick/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts/server.js:16:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 4000
}
Cast to TV: closing node app...
  bridge Closing node server +0ms
Cast to TV: closed successfully

```
Hi Rastofar, I'm having trouble making this GNOME extension work at all. Completely fresh install, all reqs and install guide followed. I have attached a screenshot of my top right menu entry. No icon for this appears in system tray (the same place dropbox appears etc).

This is on Fedora 33 with GNOME Shell 3.38.3

My only option is "turn on", I don't see any media types or anything. In the settings I was able to scan chromecast devices and be presented with the name of my TV device. Alas nothing when I simply click turn on.

**Comment by Rafostar** [comment]
It says that you already have some other app using 4000 port. Try changing it in extension settings.

**Comment by Rafostar** [comment]
@nhillsdonuk 

Did changing the port helped?
